### PR TITLE
Reset color don't set to black.

### PR DESCRIPTION
**Pull request by colinbate**
If your Terminal text colour isn't black, this change will reset it back to what it was.

### CODE REVIEW

**Comment by colinbate** [comment]
Are you planning to publish a new version with this fix? Just wanted to know whether I need keep using my fork.

**Comment by kasselTrankos** [comment]
Hi,
im done from your pull request, so i dont understand.

**Comment by colinbate** [comment]
I meant publish a new version to NPM. Presumably 3.0.3.

**Comment by kasselTrankos** [comment]
ok, i'll do soon, if i can today.

**Comment by kasselTrankos** [comment]
done, you can now get the last version 3.1.0
tks

**Comment by colinbate** [comment]
Thanks. I downloaded 3.1.0 but the colour fix isn't included in that version.

**Comment by kasselTrankos** [comment]
Please, take it again and tell me. thanks

**Comment by colinbate** [comment]
3.3.0 has it, thanks.

**Pull request merged**
